---
name: Java CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [11, 13, 15, 16, 17-ea]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.2.1
      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'oracle'
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        run: mvn test -B --file pom.xml

...
